# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import predictor_server_pb2 as predictor__server__pb2


class PredictorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TeamPrediction = channel.unary_unary(
                '/Predictor/TeamPrediction',
                request_serializer=predictor__server__pb2.TeamInput.SerializeToString,
                response_deserializer=predictor__server__pb2.PredictionOutput.FromString,
                )
        self.PlayerPrediction = channel.unary_unary(
                '/Predictor/PlayerPrediction',
                request_serializer=predictor__server__pb2.PlayerInput.SerializeToString,
                response_deserializer=predictor__server__pb2.PredictionOutput.FromString,
                )
        self.ChampionshipPrediction = channel.unary_unary(
                '/Predictor/ChampionshipPrediction',
                request_serializer=predictor__server__pb2.ChampionshipInput.SerializeToString,
                response_deserializer=predictor__server__pb2.PredictionOutput.FromString,
                )


class PredictorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TeamPrediction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayerPrediction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChampionshipPrediction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TeamPrediction': grpc.unary_unary_rpc_method_handler(
                    servicer.TeamPrediction,
                    request_deserializer=predictor__server__pb2.TeamInput.FromString,
                    response_serializer=predictor__server__pb2.PredictionOutput.SerializeToString,
            ),
            'PlayerPrediction': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayerPrediction,
                    request_deserializer=predictor__server__pb2.PlayerInput.FromString,
                    response_serializer=predictor__server__pb2.PredictionOutput.SerializeToString,
            ),
            'ChampionshipPrediction': grpc.unary_unary_rpc_method_handler(
                    servicer.ChampionshipPrediction,
                    request_deserializer=predictor__server__pb2.ChampionshipInput.FromString,
                    response_serializer=predictor__server__pb2.PredictionOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Predictor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Predictor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TeamPrediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Predictor/TeamPrediction',
            predictor__server__pb2.TeamInput.SerializeToString,
            predictor__server__pb2.PredictionOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PlayerPrediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Predictor/PlayerPrediction',
            predictor__server__pb2.PlayerInput.SerializeToString,
            predictor__server__pb2.PredictionOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChampionshipPrediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Predictor/ChampionshipPrediction',
            predictor__server__pb2.ChampionshipInput.SerializeToString,
            predictor__server__pb2.PredictionOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
