# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predictor_server.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16predictor_server.proto\"<\n\x0bPlayerInput\x12\x15\n\rfirstPlayerId\x18\x01 \x02(\x05\x12\x16\n\x0esecondPlayerId\x18\x02 \x02(\x05\"6\n\tTeamInput\x12\x13\n\x0b\x66irstTeamId\x18\x01 \x02(\x05\x12\x14\n\x0csecondTeamId\x18\x02 \x02(\x05\"\x1f\n\x11\x43hampionshipInput\x12\n\n\x02id\x18\x01 \x02(\x05\"\x1e\n\x10PredictionOutput\x12\n\n\x02id\x18\x01 \x02(\x05\x32\xbc\x01\n\rPredictorGrpc\x12\x35\n\x10PlayerPrediction\x12\x0c.PlayerInput\x1a\x11.PredictionOutput\"\x00\x12\x31\n\x0eTeamPrediction\x12\n.TeamInput\x1a\x11.PredictionOutput\"\x00\x12\x41\n\x16\x43hampionshipPrediction\x12\x12.ChampionshipInput\x1a\x11.PredictionOutput\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predictor_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYERINPUT']._serialized_start=26
  _globals['_PLAYERINPUT']._serialized_end=86
  _globals['_TEAMINPUT']._serialized_start=88
  _globals['_TEAMINPUT']._serialized_end=142
  _globals['_CHAMPIONSHIPINPUT']._serialized_start=144
  _globals['_CHAMPIONSHIPINPUT']._serialized_end=175
  _globals['_PREDICTIONOUTPUT']._serialized_start=177
  _globals['_PREDICTIONOUTPUT']._serialized_end=207
  _globals['_PREDICTORGRPC']._serialized_start=210
  _globals['_PREDICTORGRPC']._serialized_end=398
# @@protoc_insertion_point(module_scope)
