# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\"4\n\nRequestObj\x12\x0f\n\x07\x65xample\x18\x01 \x02(\t\x12\x15\n\rnumberExample\x18\x02 \x02(\x05\"\x1b\n\tReturnObj\x12\x0e\n\x06result\x18\x01 \x02(\t22\n\x06Server\x12(\n\x0bRecordRoute\x12\x0b.RequestObj\x1a\n.ReturnObj\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTOBJ']._serialized_start=16
  _globals['_REQUESTOBJ']._serialized_end=68
  _globals['_RETURNOBJ']._serialized_start=70
  _globals['_RETURNOBJ']._serialized_end=97
  _globals['_SERVER']._serialized_start=99
  _globals['_SERVER']._serialized_end=149
# @@protoc_insertion_point(module_scope)
